In [1]:
import pandas as pd
import pandas_datareader.data as web

In [2]:
info = pd.DataFrame(columns=['Name', 'Unit', 'Construction', 'Description'])
info.loc['Mkt-RF'] = ['Market', 'Excess Return', 'Market-cap-weighted', 'US Equities']
info.loc['SMB'] = ['Size', 'Excess Return', 'Small Minus Big', 'Long small stocks and short big stocks']
info.loc['HML'] = ['Value', 'Excess Return', 'High Minus Low', 'Long value (high book-to-market) stocks and short growth (low book-to-market) stocks']
info.loc['RF'] = ['Risk-free rate', 'Total Return', 'Tbills', '']
info

,Name,Unit,Construction,Description
Mkt-RF,Market,Excess Return,Market-cap-weighted,US Equities
SMB,Size,Excess Return,Small Minus Big,Long small stocks and short big stocks
HML,Value,Excess Return,High Minus Low,Long value (high book-to-market) stocks and sh...
RF,Risk-free rate,Total Return,Tbills,

In [3]:
rawdata = web.DataReader('F-F_Research_Data_Factors', data_source='famafrench',start='19260101',end='20210930')
facs = rawdata[0] / 100
# convert the yyyy-mm to timestamp object. default is to put first of month, but should be end of month
facs = facs.to_timestamp().resample('M').last()
facs

            Mkt-RF     SMB     HML      RF
Date
1926-07-31  0.0296 -0.0238 -0.0273  0.0022
1926-08-31  0.0264 -0.0147  0.0414  0.0025
1926-09-30  0.0036 -0.0139  0.0012  0.0023
1926-10-31 -0.0324 -0.0013  0.0065  0.0032
1926-11-30  0.0253 -0.0016 -0.0038  0.0031
...            ...     ...     ...     ...
2021-04-30  0.0493 -0.0311 -0.0093  0.0000
2021-05-31  0.0029 -0.0028  0.0704  0.0000
2021-06-30  0.0279  0.0180 -0.0776  0.0000
2021-07-31  0.0119 -0.0396 -0.0175  0.0000
2021-08-31  0.0291 -0.0045 -0.0007  0.0000

[1142 rows x 4 columns]

In [4]:
rawdata = web.DataReader('25_Portfolios_5x5', data_source='famafrench',start='19260101',end='20210930')
rets = rawdata[0] / 100
# convert the yyyy-mm to timestamp object. default is to put first of month, but should be end of month
rets = rets.to_timestamp().resample('M').last()
rets

,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,ME2 BM5,...,ME4 BM1,ME4 BM2,ME4 BM3,ME4 BM4,ME4 BM5,BIG LoBM,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM
Date,,,,,,,,,,,,,,,,,,,,,
1926-07-31,0.037782,-0.004119,-0.019434,0.003530,0.020534,0.012077,0.024192,0.004926,-0.026049,-0.003344,...,0.015893,0.015278,0.014533,0.002727,0.024678,0.034539,0.060902,0.019593,0.031111,0.005623
1926-08-31,-0.022074,-0.087275,0.024404,0.006086,0.083968,0.023618,-0.011849,0.040084,0.005038,0.061675,...,0.013336,0.038730,0.018467,0.021706,0.053422,0.010124,0.041903,0.020462,0.054849,0.077576
1926-09-30,-0.062113,-0.002989,-0.061982,-0.016368,0.008649,-0.026540,-0.012618,0.010829,-0.035480,-0.009401,...,0.010923,-0.005250,-0.014921,0.014646,0.008730,-0.012906,0.036538,0.000200,-0.007487,-0.024284
1926-10-31,-0.086241,-0.037532,-0.056719,0.057170,-0.025476,-0.028069,-0.032663,-0.050745,-0.080191,-0.013213,...,-0.033361,-0.026559,-0.019169,-0.031051,-0.053525,-0.027413,-0.030071,-0.022649,-0.046719,-0.058129
1926-11-30,0.034744,0.066476,0.022634,-0.047020,0.005362,0.031033,-0.023690,0.030078,0.051546,0.027292,...,0.034448,0.023887,0.039130,0.049320,0.018213,0.042946,0.025326,0.015117,0.036619,0.025636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-30,-0.031918,-0.025146,0.016436,0.010073,-0.009711,0.035662,0.016463,0.022390,0.007952,0.012227,...,0.043807,0.031023,0.059322,0.033530,0.060459,0.058966,0.058241,0.039870,0.047821,0.045701
2021-05-31,0.014358,0.005285,0.007486,0.023463,0.104483,-0.024340,0.001611,0.005692,0.026063,0.073152,...,-0.019889,0.000367,0.021225,0.037037,0.044815,-0.013830,0.007609,0.033797,0.036626,0.080384
2021-06-30,0.086902,0.051847,0.010202,-0.004778,0.037169,0.066363,0.035228,0.013767,-0.020188,0.011213,...,0.051402,0.002436,-0.010576,-0.038628,-0.046390,0.057328,0.014829,-0.022818,-0.023452,-0.037225
2021-07-31,-0.101732,-0.076929,-0.036096,-0.047526,-0.015473,-0.074616,-0.032841,-0.017331,-0.021717,-0.060350,...,-0.007491,0.018909,-0.012862,0.013608,-0.042888,0.033018,0.031933,0.004058,-0.015416,-0.034379
2021-08-31,0.025426,0.055795,0.040673,0.026149,0.039750,0.019219,0.023608,0.012415,0.015206,0.024336,...,0.032077,0.015669,0.016435,0.032307,0.050117,0.033115,0.041280,0.005564,0.012868,0.043102

In [5]:
with pd.ExcelWriter('dfa_analysis_data.xlsx') as writer:  
    info.to_excel(writer, sheet_name= 'descriptions')
    facs.to_excel(writer, sheet_name='factors')
    rets.to_excel(writer, sheet_name='portfolios (total returns)')