In [1]:
import pandas as pd
import numpy as np

import yfinance as yf

# Equity ETFs

In [2]:
info = pd.DataFrame(columns=['Description'])

info.loc['SPY'] = 'Domestic Equity SPDR S&P500'

# industry etfs
info.loc['XLY'] = 'Consumer Staples'
info.loc['XLP'] = 'Consumer Discretionary'
info.loc['XLE'] = 'Energy'
info.loc['XLF'] = 'Finance'
info.loc['XLV'] = 'Health Care'
info.loc['XLI'] = 'Industrial'
info.loc['XLB'] = 'Materials'
info.loc['XLK'] = 'Technology'
info.loc['XLU'] = 'Utilities'

# single-name stocks
info.loc['AAPL'] = 'Apple'
info.loc['AMZN'] = 'Amazon'
info.loc['MSFT'] = 'Microsoft'
info.loc['GS'] = 'Goldman Sachs'
info.loc['JPM'] = 'JP Morgan'

info

                      Description
SPY   Domestic Equity SPDR S&P500
XLY              Consumer Staples
XLP        Consumer Discretionary
XLE                        Energy
XLF                       Finance
XLV                   Health Care
XLI                    Industrial
XLB                     Materials
XLK                    Technology
XLU                     Utilities
AAPL                        Apple
AMZN                       Amazon
MSFT                    Microsoft
GS                  Goldman Sachs
JPM                     JP Morgan

In [3]:
tickers = list(info.index.values)
df = yf.download(tickers, start="1999-12-31", end="2021-09-30")['Adj Close']

[*********************100%***********************]  15 of 15 completed

In [4]:
prices = df
rets = prices.pct_change().iloc[1:,:]
rets

,AAPL,AMZN,GS,JPM,MSFT,SPY,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,
2000-01-03,0.088754,0.174056,-0.062375,-0.061947,-0.001606,-0.009787,-0.022927,-0.019608,-0.037476,-0.025858,0.029002,-0.012211,-0.024431,-0.019221,-0.030181
2000-01-04,-0.084310,-0.083217,-0.062987,-0.021942,-0.033780,-0.039106,-0.009627,-0.018824,-0.043716,-0.027627,-0.050733,-0.028160,-0.030165,-0.022692,-0.030083
2000-01-05,0.014633,-0.148741,-0.046828,-0.006173,0.010543,0.001789,0.041312,0.026379,-0.007857,-0.004457,-0.014846,0.017668,0.025234,-0.008971,-0.012299
2000-01-06,-0.086538,-0.060036,0.042789,0.014197,-0.033498,-0.016071,0.025671,0.038552,0.043917,0.013431,-0.033152,0.018750,-0.001717,0.003195,0.011370
2000-01-07,0.047369,0.061010,0.003799,0.018373,0.013068,0.058076,-0.000569,0.010686,0.016551,0.038100,0.017456,0.063395,0.008600,0.012208,0.047109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-23,0.006719,0.010636,0.016577,0.033801,0.003282,0.012150,0.014241,0.035034,0.024522,0.015335,0.013396,0.003697,-0.005339,0.007220,0.010145
2021-09-24,0.000613,0.002787,-0.002577,0.011540,-0.000701,0.001647,-0.001478,0.007522,0.005260,0.002087,0.000702,0.000425,-0.001073,-0.004075,0.003746
2021-09-27,-0.010550,-0.005757,0.022924,0.024166,-0.017304,-0.002861,0.007771,0.035560,0.013605,0.000992,-0.009699,-0.004531,-0.011821,-0.014245,0.005354
2021-09-28,-0.023801,-0.026379,-0.025787,-0.005390,-0.036204,-0.020152,-0.012362,0.003415,-0.016520,-0.011590,-0.029641,-0.011807,-0.012584,-0.017141,-0.019259
2021-09-29,0.006483,-0.004475,-0.011836,-0.000783,0.001693,0.001683,-0.004090,0.000000,0.000787,0.001102,-0.001262,0.009069,0.013058,0.007899,0.000987

In [5]:
with pd.ExcelWriter('industry_equity_data_daily.xlsx') as writer:  
    info.to_excel(writer, sheet_name= 'descriptions')
    rets.to_excel(writer, sheet_name='total returns')
#    retsx.to_excel(writer, sheet_name='excess returns')